### PR TITLE
Fix: Storage leak in Builder and Fetcher

### LINKED ISSUE #2821: Storage Leak in Fetcher
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2023-05-18T12:33:09Z"
    GitCommit: f955d118
    Version: v1.19.0
server:
  fission/core:
    BuildDate: "2023-05-18T12:33:09Z"
    GitCommit: f955d118
    Version: v1.19.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.3-eks-a5565ad", GitCommit:"78c8293d1c65e8a153bf3c03802ab9358c0e1a14", GitTreeState:"clean", BuildDate:"2023-06-16T17:32:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
EKS (eks.3)
**Describe the bug**

I observed that env builder pod (that has builder and fetcher container) keeps getting evicted because of over utlization of ephemeral storage. On checking the container, I found that it still has files related to the packages it built previously which are piling up (since I was building more than 100 functions together simultaneously).

**To Reproduce**
Create an environment (version 3) and build a lot of packages.

**Expected result**

Ideally once the package is built, all its files should be removed from the builder pod

**Actual result**
Builder Pod is keeping all the files of previously generated packages

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

On digging the fetcher code, it was confirmed in the `UploadHandler` that even after a successful response from the `ssClient.Upload` func, the files are not deleted.

### PR DESCRIPTION
**Pull request by soharab-ic**
## Description

- Builder pod contains builder and fetcher containers and they share a volume.
- Builder build the packages and fetcher uploads the packages to storage service.
- In case of build/upload failure, packages remains in the shared volume. These packages are of no use and needs to be cleaned up. 
- Added a `Clean` API in builder package. This API will be called by `buildermgr` for deleting src pkg after pkg is build and deployment is uploaded. I wanted to delete the src package from builder pod directly after failed/successful build but `buildermgr` uses `retryablehttp` client so in case of build failure `buildermgr` will retry build by sending `Build` request.
- To delete deployment pkg, fetcher `UploadHandler` will delete the deployment pkg after successful/failed upload.

## Which issue(s) this PR fixes:

Fixes #2821

## Testing

- Added a negative test for builder's `Clean` API.
- Adding a positive test involves creating a `/packages` directory for which `root` permissions are required.Therefore, did not add any positive test.
```
{"level":"info","ts":"2024-07-10T10:45:48.563Z","logger":"builder","caller":"builder/builder.go:197","msg":"builder received clean request","request":{"srcPkgFilename":"hello-test-fdebb12e-60ff-4e95-b41b-e3531444a4a4-kfezxl"}}
{"level":"info","ts":"2024-07-10T10:45:48.564Z","logger":"builder","caller":"builder/builder.go:175","msg":"clean request complete","elapsed_time":0.001311227}
```

## Checklist:

- [ ] I ran tests as well as code linting locally to verify my changes. 
- [x] I have done manual verification of my changes, changes working as expected.
- [x] I have added new tests to cover my changes.
- [ ] My changes follow contributing guidelines of Fission.
- [x] I have signed all of my commits.

### CODE REVIEW

File: pkg/utils/utils.go [hunk 1]
```diff
@@ -267,3 +267,28 @@ func FindFreePort() (int, error) {
 
 	return port, nil
 }
+
+func DeleteOldPackages(pkgPath, pkgType string) error {
```
Comment (sanketsudake) [inline pkg/utils/utils.go:271]: Please add detailed comments for this function.

File: cmd/builder/app/server.go [hunk 2]
```diff
@@ -32,6 +32,7 @@ func Run(ctx context.Context, logger *zap.Logger, mgr manager.Interface, shareVo
 	builder := builder.MakeBuilder(logger, shareVolume)
 	mux := http.NewServeMux()
 	mux.HandleFunc("/", builder.Handler)
+	mux.HandleFunc("/clean", builder.Clean)
```
Comment (sanketsudake) [inline cmd/builder/app/server.go:35]: Please try once commenting on this line. 
Following scenario may happen,
It may happen user upgrades to newer version of fission but builder pod is old. 
In that case, clean API would not be present and client would get 404 response.
We should be able to handle this case, from client side.

File: pkg/builder/client/client.go [hunk 3]
```diff
@@ -86,3 +92,25 @@ func (c *client) Build(ctx context.Context, req *builder.PackageBuildRequest) (*
...
+	}
+
+	resp, err := ctxhttp.Post(ctx, c.httpClient.StandardClient(), c.getCleanUrl(), "application/json", bytes.NewReader(body))
+	if err != nil {
+		logger.Error("error creating delete request", zap.Error(err))
+		return err
+	}
+	defer resp.Body.Close()
+
+	if resp.StatusCode != http.StatusOK {
```
Comment (sanketsudake) [inline pkg/builder/client/client.go:111]: We should be able to ignore not found error etc if API is missing due to older version builder on function side.

File: cmd/builder/app/server.go (hunk 2 above)
Comment (soharab-ic) [reply cmd/builder/app/server.go:35]: Even if clean API is missing, the request will be forwarded to `builder.Handler` since it accepts all request because of `/` route and we get a 500 response instead of 404.

Comment (soharab-ic) [reply cmd/builder/app/server.go:35]: Even if i change the clean API method from `POST` to `DELETE`, still the response would 405 instead of 404.
Which approach should i take @sanketsudake ?
1. Handle 500 response in client.
2. Change clean API method from POST to DELETE.

I think approach 2 is good because in first approach builder will try to build the package but in 2nd approach it will return 405 response and avoid building the package.

Comment (soharab-ic) [reply cmd/builder/app/server.go:35]: Also i think it would be better if we replace `/` route with `/build` route.

Comment (sanketsudake) [reply cmd/builder/app/server.go:35]: > Change clean API method from POST to DELETE.
This one sounds better. We should change existing API behaviour for no reason.

File: pkg/utils/utils.go (hunk 1 above)
Comment (soharab-ic) [reply pkg/utils/utils.go:275]: Done

File: cmd/builder/app/server.go (hunk 2 above)
Comment (soharab-ic) [reply cmd/builder/app/server.go:35]: Done

File: pkg/builder/client/client.go (hunk 3 above)
Comment (soharab-ic) [reply pkg/builder/client/client.go:115]: Done

**Review by sanketsudake — APPROVED** [review]
