### PR TITLE
Fix pre-check failure during new fission installation

### LINKED ISSUE #2436: Fission compatibility check failing
**Fission/Kubernetes version**
```
$ fission version
client:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0
server:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0
```
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
``` 

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Kind cluster

**Describe the bug**
`fission check --pre` command doesn't run without installing fission which defeats it's purpose.

**To Reproduce**
Run `fission check --pre` without installing fission.

**Expected result**
It should show if it's compatible with my kubernetes platform or not.

**Actual result**
```
Error forwarding to port 42679: no available pod for port-forwarding with label selector application=fission-api
Options:
  --pre=false   Only run pre-installation checks, to determine if fission can be installed

Global Options:
  --server=''         Server URL
  --verbosity=1 (-v)  CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)
  --kube-context=''   Kubernetes context to be used for the execution of Fission commands

Usage:
  fission check [options]

Error: no available pod for port-forwarding with label selector application=fission-api
```

### PR DESCRIPTION
**Pull request by shubham4443**
Signed-off-by: Shubham Nazare <shubham4443@gmail.com>

## Description

This PR fixes the issue where user sees error while executing `fission check --pre` without having fission installed.

## Which issue(s) this PR fixes:

Fixes #2436 

## Checklist:

- [ ] I ran tests as well as code linting locally to verify my changes. 
- [x] I have done manual verification of my changes, changes working as expected.
- [ ] I have added new tests to cover my changes.
- [x] My changes follow contributing guidelines of Fission.
- [x] I have signed all of my commits.

### CODE REVIEW

File: cmd/fission-cli/app/app.go [hunk 1]
```diff
@@ -86,7 +86,7 @@ func App() *cobra.Command {
 	})
 
 	wrapper.SetFlags(rootCmd, flag.FlagSet{
-		Global: []flag.Flag{flag.GlobalServer, flag.GlobalVerbosity, flag.KubeContext},
+		Global: []flag.Flag{flag.GlobalServer, flag.GlobalVerbosity, flag.KubeContext, flag.PreCheckOnly},
```
Comment (sanketsudake) [inline cmd/fission-cli/app/app.go:89]: Just exploring, if we can avoid global flag since this flag is used in check command only ?

File: cmd/fission-cli/app/app.go [hunk 2]
```diff
@@ -86,7 +86,8 @@ func App() *cobra.Command {
 	})
 
 	wrapper.SetFlags(rootCmd, flag.FlagSet{
-		Global: []flag.Flag{flag.GlobalServer, flag.GlobalVerbosity, flag.KubeContext},
+		Global:   []flag.Flag{flag.GlobalServer, flag.GlobalVerbosity, flag.KubeContext},
+		Optional: []flag.Flag{flag.PreCheckOnly},
```
Comment (blackfly19) [inline cmd/fission-cli/app/app.go:90]: I don't think the flag is required here because it would just show up in the fission help which wouldn't make sense. This flag is already included in `fission check -h` so you can remove this from here.

**Review by blackfly19 — CHANGES_REQUESTED** [review]

**Review by sanketsudake — APPROVED** [review]

**Comment by sanketsudake** [comment]
@mergifyio rebase

**Comment by sanketsudake** [comment]
Thanks @shubham4443 for the fix 🎉
