### PR TITLE
Consider Pod Phase in IsReadyPod

### LINKED ISSUE #1054: Failed to relabel pod
test_spec_multifile.sh fails intermittently and fails to relabel pods from the pool. This works at times but also fails fairly often:

```
1 function created: spec-975535868
2019/01/11:10:44:18 Checking function's existance
spec-975535868         d8d31705-158d-11e9-bc52-42010a8001ab python-spec-975535868 poolmgr      0        0        0      0      0         0         0
2019/01/11:10:44:19 Testing function
[FAILED]: /test_specs/test_spec_multifile.sh
```
The relabeling operation fails for all 3 pods from the pool manager - as can be seen from logs below, after it is echausted of the pool, it returns error:

```
2019/01/11 10:44:19 [spec-975535868] getting function service from pool
2019/01/11 10:44:19 [spec-975535868] Choosing pod from pool
2019/01/11 10:44:19 [map[functionUid:d8d31705-158d-11e9-bc52-42010a8001ab executorInstanceId:thctpbkw unmanaged:true functionName:spec-975535868]] found 1 ready pods of 1 total
2019/01/11 10:44:19 relabeling pod: [python-spec-975535868-poolmgr-default-6c775c8c68-k6rjj]
2019/01/11 10:44:19 failed to relabel pod [python-spec-975535868-poolmgr-default-6c775c8c68-k6rjj]: Operation cannot be fulfilled on pods "python-spec-975535868-poolmgr-default-6c775c8c68-k6rjj": the object has been modified; please apply your changes to the latest version and try again
2019/01/11 10:44:19 [map[unmanaged:true functionName:spec-975535868 functionUid:d8d31705-158d-11e9-bc52-42010a8001ab executorInstanceId:thctpbkw]] found 3 ready pods of 3 total
2019/01/11 10:44:19 relabeling pod: [python-spec-975535868-poolmgr-default-6c775c8c68-k6rjj]
2019/01/11 10:44:19 failed to relabel pod [python-spec-975535868-poolmgr-default-6c775c8c68-k6rjj]: Operation cannot be fulfilled on pods "python-spec-975535868-poolmgr-default-6c775c8c68-k6rjj": the object has been modified; please apply your changes to the latest version and try again
2019/01/11 10:44:19 [map[functionUid:d8d31705-158d-11e9-bc52-42010a8001ab executorInstanceId:thctpbkw unmanaged:true functionName:spec-975535868]] found 2 ready pods of 3 total
2019/01/11 10:44:19 relabeling pod: [python-spec-975535868-poolmgr-default-6c775c8c68-pxmrw]
2019/01/11 10:44:19 failed to relabel pod [python-spec-975535868-poolmgr-default-6c775c8c68-pxmrw]: Operation cannot be fulfilled on pods "python-spec-975535868-poolmgr-default-6c775c8c68-pxmrw": the object has been modified; please apply your changes to the latest version and try again
2019/01/11 10:44:19 [map[functionUid:d8d31705-158d-11e9-bc52-42010a8001ab executorInstanceId:thctpbkw unmanaged:true functionName:spec-975535868]] found 1 ready pods of 3 total
2019/01/11 10:44:19 relabeling pod: [python-spec-975535868-poolmgr-default-6c775c8c68-h6whd]
2019/01/11 10:44:19 Chosen pod: python-spec-975535868-poolmgr-default-6c775c8c68-h6whd (in 239.06091ms)
2019/01/11 10:44:19 [spec-975535868] Error creating service for function: Pod has no IP
2019/01/11 10:44:19 Error: 500: [spec-975535868] Error creating service for function: Pod has no IP
10.52.4.246 - - [11/Jan/2019:10:44:19 +0000] "POST /v2/getServiceForFunction HTTP/1.1" 500 68
2019/01/11 10:44:19 Error in pod 'python-spec-975535868-poolmgr-default-6c775c8c68-h6whd', scheduling cleanup
```

Most likely the POD not having an IP is an after effect, but related log:

```
time="2019-01-11T10:44:19Z" level=info msg="Calling getServiceForFunction for function: spec-975535868" 
time="2019-01-11T10:44:19Z" level=info msg="Error from GetServiceForFunction for function (&ObjectMeta{Name:spec-975535868,GenerateName:,Namespace:default,SelfLink:/apis/fission.io/v1/namespaces/default/functions/spec-975535868,UID:d8d31705-158d-11e9-bc52-42010a8001ab,ResourceVersion:84080994,Generation:1,CreationTimestamp:2019-01-11 10:44:18 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{fission-name: python,fission-uid: 54fce352-c790-4081-bc47-321e5c28d738,},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,}): 500 : [spec-975535868] Error creating service for function: Pod has no IP" 
time="2019-01-11T10:44:19Z" level=info msg="Error updating service address entry for function spec-975535868_default: Internal error - [spec-975535868] Error creating service for function: Pod has no IP" 
2019/01/11 10:44:21 Unable to lookup function in functionRecorderMap
```

### PR DESCRIPTION
**Pull request by bhavin192**
- This makes sure if the Pod is in Running state
  - https://godoc.org/k8s.io/api/core/v1#PodPhase
- Checks if an IP address is allocated to the Pod
- https://github.com/fission/fission/issues/1054#issuecomment-457817792 

~~Probably Fixe s #1054~~

---
This change is [Reviewable](https://reviewable.io/reviews/fission/fission/1080)

### CODE REVIEW

**Comment by life1347** [comment]
Just out of curiosity, under what situation the pod is not in RUNNING/has no IP address if all containers are ready?

**Comment by life1347** [comment]
Found an example here
```
Name:                      nodejs-poolmgr-default-59964f7bc9-n8tgg
Namespace:                 f-func-ogeoru
Node:                      gke-fission-ci-1-default-pool-5923deff-6r9n/10.128.0.4
Start Time:                Tue, 08 Jan 2019 11:01:56 +0000
Labels:                    executorInstanceId=yb3jumnn
                           functionName=f1-1546945313
                           functionUid=ce9c5d57-1334-11e9-bc52-42010a8001ab
                           unmanaged=true
Annotations:               <none>
Status:                    Terminating (lasts 2m5s)
Termination Grace Period:  360s
IP:                        10.52.3.251
Containers:
  nodejs:
    Container ID:   docker://bfac98cf7644c00ae68b5787b1da3f26dea1d6ffbc35f17d6afaf888f90c2e60
    Image:          fission/node-env
    Image ID:       docker-pullable://fission/node-env@sha256:c60211c56fec7260710da416100a4833b8511303f1f9e8c76fe298f0ff0edc4f
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 08 Jan 2019 11:01:58 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /configs from configmaps (rw)
      /secrets from secrets (rw)
      /userfunc from userfunc (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from fission-fetcher-token-fgl6b (ro)
  fetcher:
    Container ID:  docker://aa34de40d60e4dc887e9bd0f29db756c5ac62a270def5378f18db6a5a31f5fdd
    Image:         gcr.io/fission-ci/fetcher:test
    Image ID:      docker-pullable://gcr.io/fission-ci/fetcher@sha256:a5300bd4892c59a6478c2f76a4001a899dcf42e64bc573c2a9c3bd14080cdd3e
    Port:          <none>
    Host Port:     <none>
    Command:
      /fetcher
      -secret-dir
      /secrets
      -cfgmap-dir
      /configs
      /userfunc
    State:          Running
      Started:      Tue, 08 Jan 2019 11:01:58 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     40m
      memory:  128Mi
    Requests:
      cpu:        10m
      memory:     16Mi
    Liveness:     http-get http://:8000/healthz delay=1s timeout=1s period=5s #success=1 #failure=3
    Readiness:    http-get http://:8000/readniess-healthz delay=1s timeout=1s period=1s #success=1 #failure=30
    Environment:  <none>
    Mounts:
      /configs from configmaps (rw)
      /secrets from secrets (rw)
      /userfunc from userfunc (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from fission-fetcher-token-fgl6b (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  userfunc:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  secrets:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  configmaps:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  fission-fetcher-token-fgl6b:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  fission-fetcher-token-fgl6b
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age    From                                                  Message
  ----    ------                 ----   ----                                                  -------
  Normal  Scheduled              8m54s  default-scheduler                                     Successfully assigned nodejs-poolmgr-default-59964f7bc9-n8tgg to gke-fission-ci-1-default-pool-5923deff-6r9n
  Normal  SuccessfulMountVolume  8m54s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  MountVolume.SetUp succeeded for volume "userfunc"
  Normal  SuccessfulMountVolume  8m54s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  MountVolume.SetUp succeeded for volume "configmaps"
  Normal  SuccessfulMountVolume  8m54s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  MountVolume.SetUp succeeded for volume "secrets"
  Normal  SuccessfulMountVolume  8m54s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  MountVolume.SetUp succeeded for volume "fission-fetcher-token-fgl6b"
  Normal  Pulling                8m53s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  pulling image "fission/node-env"
  Normal  Pulled                 8m52s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  Successfully pulled image "fission/node-env"
  Normal  Created                8m52s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  Created container
  Normal  Started                8m52s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  Started container
  Normal  Pulling                8m52s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  pulling image "gcr.io/fission-ci/fetcher:test"
  Normal  Pulled                 8m52s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  Successfully pulled image "gcr.io/fission-ci/fetcher:test"
  Normal  Created                8m52s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  Created container
  Normal  Started                8m52s  kubelet, gke-fission-ci-1-default-pool-5923deff-6r9n  Started container
```
I guess the POD was waiting for the terminationGracePeriod, that's why all containers are in ready state and POD is in TERMINATING.

File: common.go [hunk 1]
```diff
@@ -120,12 +120,23 @@ func IsReadyPod(pod *apiv1.Pod) bool {
 		return false
 	}
 
+	// pod is not in Running Phase. It can be in Pending,
+	// Succeeded, Failed, Unknown
+	if pod.Status.Phase != apiv1.PodRunning {
```
Comment (life1347) [inline common.go]: Would you mind adding some comment to describe the problem we saw in pod information?

Comment (bhavin192) [reply common.go]: Something like this?
```
	// pod is not in Running Phase. It can be in Pending,
	// Succeeded, Failed, Unknown. In some cases 
       // the pod can be in different sate than Running even 
       // if all the containers are in Ready state
```

Comment (bhavin192) [reply common.go]: > Though it's not in the PR change, how about add more information (e.g. pod name, namespace) in error return here

That would be a nice addition, doing that change.

Comment (life1347) [reply common.go]: How about this? Feel free to change it, if it's not good enough. 
```
// pod is not in Running Phase. It can be in Pending,
// Succeeded, Failed, Unknown. In some cases 
// the pod can be in different sate than Running, for 
// example kubernetes sets a pod to Termination while 
// k8s waits for the grace period of the pod, even if all 
// the containers are in Ready state
```
