### PR TITLE
Fixed poolmgr pod naming error

### LINKED ISSUE #2379: poolmgr cannot create deployment due to long name
**Fission/Kubernetes version**
1.15.1/1.20.15+k3s1

**Kubernetes platform (e.g. Google Kubernetes Engine)**
k3s

**Describe the bug**

Poolmgr deployment can fail to be created if the environment name or namespace the environment is in is too long.

**To Reproduce**

1. Create an environment with a long name (mine is 50 characters)
2. Run a function in said environment

**Expected result**

poolmgr deployment is created

**Actual result**
deployment fails to create

**Screenshots/Dump file**

The problem is basically the same as for #2009 
https://github.com/fission/fission/blob/a1cbce810ebce938aefb8d9c883d3942c8d7a01c/pkg/executor/executortype/poolmgr/gp_deployment.go#L37

If either the environment name or the namespace are long and combine to be too long the deployment name exceeds the limit.

<pre>
{"level":"error","ts":"2022-03-11T03:56:18.634Z","logger":"triggerset.http_trigger_set.XXX-XXX","caller":"httputil/reverseproxy.go:295","msg":"error sending request to function","trace_id":"f86fc17feb32cb1f8f23d3e2a6313262","error":" - Internal error - [xxx-xxx] error creating service for function: Deployment.apps \"poolmgr-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-default-33243\" is invalid: spec.template.spec.containers[2].image: Required value","function":{"namespace":"default","name":"xxx-xxx"},"status":"Internal Server Error","code":500,"stacktrace":"net/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.11/libexec/src/net/http/httputil/reverseproxy.go:295\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\tpkg/router/functionHandler.go:529\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.11/libexec/src/net/http/server.go:2050\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/sanket/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\tpkg/router/mutablemux.go:52\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.11/libexec/src/net/http/server.go:2868\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go@1.16/1.16.11/libexec/src/net/http/server.go:1933"}
</pre>

**Additional context**
I don't recommend relying on any specific convention/naming pattern for identifying an object. It would be better to use labels to identify.

### PR DESCRIPTION
**Pull request by blackfly19**
## Description
Poolmgr pod naming convention changed

## Which issue(s) this PR fixes:
Fixes #2379 

## Checklist:

- [ ] I ran tests as well as code linting locally to verify my changes. 
- [ ] I have done manual verification of my changes, changes working as expected.
- [ ] I have added new tests to cover my changes.
- [ ] My changes follow contributing guidelines of Fission.
- [ ] I have signed all of my commits.

### CODE REVIEW

File: pkg/executor/executortype/poolmgr/gp_deployment.go [hunk 1]
```diff
@@ -34,7 +35,18 @@ import (
...
 func (gp *GenericPool) getPoolName(env *fv1.Environment) string {
 	// TODO: get rid of resource version here
-	return strings.ToLower(fmt.Sprintf("poolmgr-%v-%v-%v", env.ObjectMeta.Name, env.ObjectMeta.Namespace, env.ObjectMeta.ResourceVersion))
+	var envPodName string
+
+	//To fit the 63 character limit
+	if len(env.ObjectMeta.Name)+len(env.ObjectMeta.Namespace) < 37 {
+		envPodName = env.ObjectMeta.Name + "-" + env.ObjectMeta.Namespace
+	} else {
+		nameLength := int(math.Min(float64(len(env.ObjectMeta.Name)), 18))
```
Comment (sanketsudake) [inline pkg/executor/executortype/poolmgr/gp_deployment.go:44]: Let's have a small inline function for min that deals with integers. We should avoid floating operations.
https://go.dev/play/p/18QW5-JWdl_c

File: pkg/executor/executortype/poolmgr/gp_deployment.go [hunk 2]
```diff
@@ -34,7 +35,18 @@ import (
 // getPoolName returns a unique name of an environment
 func (gp *GenericPool) getPoolName(env *fv1.Environment) string {
```
Comment (sanketsudake) [inline pkg/executor/executortype/poolmgr/gp_deployment.go:36]: Lets convert this function from method to simple pure function, ie,

```
func getPoolName(env *fv1.Environment) string {
...
}
```
We should unit tests around this function.

File: pkg/executor/executortype/poolmgr/gp_deployment.go [hunk 3]
```diff
@@ -34,7 +35,18 @@ import (
...
+	//To fit the 63 character limit
+	if len(env.ObjectMeta.Name)+len(env.ObjectMeta.Namespace) < 37 {
+		envPodName = env.ObjectMeta.Name + "-" + env.ObjectMeta.Namespace
+	} else {
+		nameLength := int(math.Min(float64(len(env.ObjectMeta.Name)), 18))
+		namespaceLength := int(math.Min(float64(len(env.ObjectMeta.Namespace)), 18))
+		envPodName = env.ObjectMeta.Name[:nameLength] + "-" + env.ObjectMeta.Namespace[:namespaceLength]
+	}
+
+	return strings.ToLower(fmt.Sprintf("poolmgr-%v-%v", envPodName, env.ResourceVersion))
```
[the remark this answers is not in the document]
Comment (sanketsudake) [reply pkg/executor/executortype/poolmgr/gp_deployment.go:49]:
```
"poolmgr-" + strings.ToLower(fmt.Sprintf("%v-%v", envPodName, env.ResourceVersion))
```

**Review by sanketsudake — CHANGES_REQUESTED** [review]

File: pkg/executor/executortype/poolmgr/gp_deployment.go [hunk 4]
```diff
@@ -32,16 +32,35 @@ import (
...
-func (gp *GenericPool) getPoolName(env *fv1.Environment) string {
+func getPoolName(env *fv1.Environment) string {
 	// TODO: get rid of resource version here
-	return strings.ToLower(fmt.Sprintf("poolmgr-%v-%v-%v", env.ObjectMeta.Name, env.ObjectMeta.Namespace, env.ObjectMeta.ResourceVersion))
+	var envPodName string
+
+	min := func(a, b int) int {
+		if a > b {
+			return b
+		} else {
```
Comment (sanketsudake) [inline pkg/executor/executortype/poolmgr/gp_deployment.go:42]: This else is unnecessary. We just keept it like
```go
func(a, b int) int {
     if a > b { return b }
      return  a
}
```

**Review by sanketsudake — APPROVED** [review]
