### PR TITLE
Pods immediately terminate for idletimeout in new deployment and container executer type

### LINKED ISSUE #2451: Function pod immediately terminates after first execution and don't honor idle timeout
**Fission/Kubernetes version**
<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1
server:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:35:50Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
n
</pre>

**Kubernetes platform:**
Docker Desktop

**Describe the bug**
Function pod immediately terminates after the first requests and don't honor idle timeout. This happens both on NewDeploy and Container Function after update of the function idle timeout.

**To Reproduce**

- Create environment with minscale 0 and default idle timeout.
- Create function (e.g. go hello world) with NewDeploy executor.
- Update function idle timeout to a different value from default, either via CLI or CR.
- Test function
- Check function pods

**Expected result**
It was expected the function pod to honor the idle timeout.

**Actual result**
The function terminates immediately after function execution. In some occasions the function doesn't execute and gives an error.

**Screenshots/Dump file**
<pre>
Error: Error calling function f1: 500; Please try again or fix the error: error sending request to function
Error: Error getting function logs from controller: error getting logs from controller, status code: '500'. Try to get logs from log database.
Error querying logs: Post "http://127.0.0.1:34125/proxy/influxdb?db=fissionFunctionLog&params=%7B%22funcuid%22%3A%22d6c80386-802b-4ade-906b-ef47f7ab2c1a%22%2C%22time%22%3A0%7D&q=select+%2A+from+%2F%5Elog%2A%2F+where+%28%22funcuid%22+%3D+%24funcuid++OR+%22kubernetes_labels_functionUid%22+%3D+%24funcuid%29+AND+%22time%22+%3E+%24time++order+by+%22time%22+asc+LIMIT+1000": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[fission-dump_1654674530.zip](https://github.com/fission/fission/files/8859480/fission-dump_1654674530.zip)
</pre>

### PR DESCRIPTION
**Pull request by shubham-bansal96**
## Description
Function pod immediately terminates once user change the idle timeout in case of new deployment and container executor type. 
This fix will prevent to immediate termination of pods and user will no more face any error for the same. Pod will get terminate as per the idle timeout provided by user.

## Which issue(s) this PR fixes:

Fixes #2451

## Testing
1. Created a simple function for executor type as pool manager, just to check my changes didn't broke the existing functionality.

2. Created a function for executor type as new deployment with idle timeout of 60 sec, and then tested the function.

3. Created a function for executor type as new deployment with idle timeout of 60 sec, and then wait to terminate the pods, once the pod get terminated, now updated the function idle timeout to something else like 50 sec, and then test the function. Now Pods were not terminated immediately. Pods got terminated after 50 sec(same as given by user).

4. Created few more functions as new deployment type and check them all together by changing their idle timeout and few other spec like minscale, maxscale etc, Everything was working as expected.

5. Created a function for executor type as new container and repeat the same steps as mentioned on point 2,3 and 4.
 
## Checklist:

- [x] I ran tests as well as code linting locally to verify my changes. 
- [x] I have done manual verification of my changes, changes working as expected.
- [ ] I have added new tests to cover my changes.
- [x] My changes follow contributing guidelines of Fission.
- [ ] I have signed all of my commits.

### CODE REVIEW

File: pkg/executor/executortype/newdeploy/newdeploymgr.go [hunk 1]
```diff
@@ -588,6 +590,7 @@ func (deploy *NewDeploy) updateFunction(ctx context.Context, oldFn *fv1.Function
 	if oldFn.Spec.Environment != newFn.Spec.Environment ||
 		oldFn.Spec.Package.PackageRef != newFn.Spec.Package.PackageRef ||
 		oldFn.Spec.Package.FunctionName != newFn.Spec.Package.FunctionName {
+		deploy.logger.Info("deployment changed", zap.String("msg", "deployment changed"))
```
Comment (sanketsudake) [inline pkg/executor/executortype/newdeploy/newdeploymgr.go:593]: Please remove this log statement or make it debug.

File: pkg/executor/executortype/poolmgr/gpm.go [hunk 2]
```diff
@@ -566,94 +568,94 @@ func (gpm *GenericPoolManager) getFunctionEnv(ctx context.Context, fn *fv1.Funct
 
 // idleObjectReaper reaps objects after certain idle time
 func (gpm *GenericPoolManager) idleObjectReaper() {
```
Comment (sanketsudake) [inline pkg/executor/executortype/poolmgr/gpm.go:570]: Please pass context to this function from calling function.

File: pkg/executor/executortype/container/containermgr.go [hunk 3]
```diff
@@ -704,72 +706,72 @@ func (caaf *Container) updateStatus(fn *fv1.Function, err error, message string)
...
 // idleObjectReaper reaps objects after certain idle time
 func (caaf *Container) idleObjectReaper() {
-	ctx := context.Background()
+	caaf.ctx = context.Background()
 
-	pollSleep := 5 * time.Second
-	for {
-		time.Sleep(pollSleep)
+	// calling function doIdleObjectReaper() repeatedly at given interval of time
+	wait.Forever(caaf.doIdleObjectReaper, time.Second*5)
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply pkg/executor/executortype/container/containermgr.go]: done

File: pkg/executor/executortype/newdeploy/newdeploymgr.go (hunk 1 above)
Comment (shubham-bansal96) [reply pkg/executor/executortype/newdeploy/newdeploymgr.go]: done

File: pkg/executor/executortype/poolmgr/gpm.go (hunk 2 above)
Comment (shubham-bansal96) [reply pkg/executor/executortype/poolmgr/gpm.go]: done

File: pkg/executor/fscache/functionServiceCache.go [hunk 4]
```diff
@@ -130,10 +130,17 @@ func (fsc *FunctionServiceCache) service() {
...
 			// get svcs idle for > req.age
-			fscs := fsc.byFunction.Copy()
+			fscs := fsc.byFunctionUID.Copy()
 			funcObjects := make([]*FuncSvc, 0)
 			for _, funcSvc := range fscs {
-				fsvc := funcSvc.(*FuncSvc)
+				mI := funcSvc.(metav1.ObjectMeta)
+				fsvcI, err := fsc.byFunction.Get(crd.CacheKey(&mI))
+				if err != nil {
+					// resp.error = err
```
Comment (sanketsudake) [inline pkg/executor/fscache/functionServiceCache.go:139]: can we remove commented line here ? I think we are not capturing any error here for resp.

Comment (shubham-bansal96) [reply pkg/executor/fscache/functionServiceCache.go]: sure.

**Comment by sanketsudake** [comment]
Related https://github.com/fission/fission/issues/1848

**Review by sanketsudake — APPROVED** [review]
