### PR TITLE
Set OwnerReferences to K8s resources created by Fission

### LINKED ISSUE #2962: Missing OwnerReference for dynamically created ressoruces like poolmgr
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2024-01-14T15:43:35Z"
    GitCommit: 7e8d5dd7
    Version: v1.20.1
server:
  fission/core:
    BuildDate: "2024-05-27T10:51:06Z"
    GitCommit: 0cfe08df
    Version: v1.20.2
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

AWS EKS

**Describe the bug**

Executer doesn't set `OwnerReference` for created ressources like `PoolMgr` (created kind `Deploy`)
As a poolmgr is created based on a env, it would be nice that the kind `Deploy` references the kind `environment` as owner.

Problem is that we use ArgoCD with HELM also for deployment of our fission functions, as the deployment of the pool manager is not child of the environment it gets marked as prune and deleted. You can set a flag to avoid the deletion, but it's still marked as prune.

**To Reproduce**

Create helm charts and add kind `environment` to the templates like that:

```yaml
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: nodejs
  namespace: fission
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app.kubernetes.io/instance: fissionactions
spec:
  builder:
    container:
      name: ""
      resources: {}
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    container:
      name: ""
      resources: {}
    image: fission/node-env
  version: 1
  ```

**Expected result**
`OwnerReference` in created ressources by executer refrencing environment or function (based on execution type)

**Actual result**
No `OwnerReference` in dynamically created ressources.

**Screenshots/Dump file**
image

### PR DESCRIPTION
**Pull request by soharab-ic**
## Description

- Set OwnerReferences to Poolmanager and builderManager deployment and service created by environment.
- Set OwnerReferences to deployment, service and HPA created by newdeploy function.
- Set OwnerReferences to builderManager deployment and service created by environment.
- Set OwnerReferences to deployment, service and HPA created by container function.

## Which issue(s) this PR fixes:

Fixes #2962 

## Testing

`OwnerReferences` are added for poolmanager deployement as follows:
```
$ kubectl get deploy poolmgr-go-122-default-253070 -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    executorInstanceId: lpd23pfg
  creationTimestamp: "2024-06-25T06:09:57Z"
  generation: 1
  labels:
    environmentName: go-122
    environmentNamespace: default
    environmentUid: e833d7f4-27bf-4f0d-9fe5-9d6169246de7
    executorType: poolmgr
    managed: "true"
  name: poolmgr-go-122-default-253070
  namespace: default
  ownerReferences:
  - apiVersion: fission.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Environment
    name: go-122
    uid: e833d7f4-27bf-4f0d-9fe5-9d6169246de7
  resourceVersion: "253399"
  uid: c29919bf-4541-4c92-af66-696555bae54f
```
**Tried following tests scenarios:**
**Test 1:**
	Create env.
	Create poolmanager, newdeploy and container function.
	Delete poolmanager, newdeploy and container function.
	**Result:**
                 1. No issues, all resources were deleted.

**Test 2:**
	Create env.
	Create poolmanager, newdeploy and container function.
	Delete Environment.
	**Result:**
		1. Fission-CLI failed to delete environment, env is used by atleast one function.
		2. kubectl deleted the environment along with poolmanager deployment, builder deployement and builder service. Poolmanager function is not deleted but it does not work as expected.
		
**Test 3:**
	Create env.
	Create poolmanager, newdeploy and container function.
	Update poolmanager, newdeploy and container function.
	**Result:**
		1. Successfully updated the functions.

## Checklist:

- [ ] I ran tests as well as code linting locally to verify my changes. 
- [x] I have done manual verification of my changes, changes working as expected.
- [ ] I have added new tests to cover my changes.
- [x] My changes follow contributing guidelines of Fission.
- [x] I have signed all of my commits.

### CODE REVIEW

File: pkg/executor/executortype/poolmgr/gp_deployment.go [hunk 1]
```diff
@@ -62,6 +62,14 @@ func (gp *GenericPool) genDeploymentMeta(env *fv1.Environment) metav1.ObjectMeta
 		Name:        getPoolName(env),
 		Labels:      deployLabels,
 		Annotations: deployAnnotations,
+		OwnerReferences: []metav1.OwnerReference{
```
Comment (sanketsudake) [inline pkg/executor/executortype/poolmgr/gp_deployment.go:65]: This change would be applicable for other executor types and other kind of resources we create through fission as well.
We need to see what all places we can set owner references and set them accordingly.

Comment (wirehack7) [reply pkg/executor/executortype/poolmgr/gp_deployment.go:65]: Yes, might also be added to buildmgr deployments if adding this to all. 

Btw, thanks for the work! 🫶🏻

Comment (soharab-ic) [reply pkg/executor/executortype/poolmgr/gp_deployment.go:65]: Set OwnerReferences to following K8s resources created by Fission:
- Set OwnerReferences to deployment, service and HPA created by newdeploy executortype.
- Set OwnerReferences to deployment, service and HPA created by container function.
- Set OwnerReferences to builderManager deployment and service created by Fission's environment resource.

File: pkg/buildermgr/envwatcher.go [hunk 2]
```diff
@@ -329,6 +329,14 @@ func (envw *environmentWatcher) createBuilderService(ctx context.Context, env *f
 			Namespace: ns,
 			Name:      name,
 			Labels:    sel,
+			OwnerReferences: []metav1.OwnerReference{
```
Comment (sanketsudake) [inline pkg/buildermgr/envwatcher.go:332]: Ideal way is to use controller ref


https://github.com/kubernetes/apimachinery/blob/37988e577e160bf7749437141fee1d6b8ca15dd6/pkg/apis/meta/v1/controller_ref.go#L54C6-L54C22

We will have to see if we can handle 

```
BlockOwnerDeletion: &blockOwnerDeletion,
		Controller:         &isController,
```

https://github.com/kubernetes-sigs/controller-runtime/blob/8290d13680ed6066d9789c0ed59ff604387e20da/pkg/controller/controller_integration_test.go#L134

Comment (soharab-ic) [reply pkg/buildermgr/envwatcher.go:332]: `BlockOwnerDeletion` and `Controller` set to true should not cause any issue.

**Review by sanketsudake — APPROVED** [review]
