### PR TITLE
Avoid fission installation failure due to analytics connection error

### LINKED ISSUE #2351: Fission fails to start if an SSL error occurs during connection to Google Analytics (e.g. behind Pi-Hole/PFBlockerNG)
<pre>
K8 Version: 1.22.4
Fission Version: 1.15.1
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

Docker Desktop

**Describe the bug**

Fission fails to start if an SSL error occurs upon connection to www.google-analytics.com.

**To Reproduce**

Run fission on a kubernetes cluster whose DNS servers provide ad/tracker blocking functionality (for example, PFBlockerNG, Pi-Hole, etc).

Additionally, this could also be reproduced by adding a hosts entry for www.google-analytics.com to a web server which serves an incorrect certificate (or no certificate).

**Expected result**

Fission should run successfully even if it cannot call home to Google Analytics.

**Actual result**

Fission fails to run with the error message: 

<pre>Error: Post "https://www.google-analytics.com/collect": x509: certificate is valid for pfsense-pfBNG-DNSBL-608700ab405a6, not www.google-analytics.com</pre>

**Screenshots/Dump file**

<pre>
?1 user@host ~ % kubectl get pods -n fission
NAME                                           READY   STATUS      RESTARTS   AGE
buildermgr-669f487cb8-6dnz9                    1/1     Running     0          10m
controller-7ddd5dd94f-pg9ng                    1/1     Running     0          10m
executor-56798496df-n5f97                      1/1     Running     0          10m
fission-v1-15-1-fission-v1.15.1-017--1-8gp5b   0/1     Error       0          7m23s
fission-v1-15-1-fission-v1.15.1-017--1-jxtmr   0/1     Error       0          9m23s
fission-v1-15-1-fission-v1.15.1-017--1-ljd52   0/1     Error       0          10m
fission-v1-15-1-fission-v1.15.1-017--1-mwl7f   0/1     Error       0          9m43s
fission-v1-15-1-fission-v1.15.1-017--1-q4bh6   0/1     Error       0          2m3s
fission-v1-15-1-fission-v1.15.1-017--1-thjgp   0/1     Error       0          9m53s
fission-v1-15-1-fission-v1.15.1-017--1-vzv2p   0/1     Error       0          8m43s
fission-v1-15-1-fission-v1.15.1-251--1-rjsn4   0/1     Completed   0          10m
kubewatcher-7795b54c9f-kd7mp                   1/1     Running     0          10m
mqtrigger-keda-7c6845b899-zqd6k                1/1     Running     0          10m
router-6584b76d68-8852b                        1/1     Running     0          10m
storagesvc-84f9d447c9-k97zh                    1/1     Running     0          10m
timer-58658f74cc-prsrb                         1/1     Running     0          10m
√ user@host ~ % kubectl logs  -n fission fission-v1-15-1-fission-v1.15.1-017--1-jxtmr  
Error: Post "https://www.google-analytics.com/collect": x509: certificate is valid for pfsense-pfBNG-DNSBL-608700ab405a6, not www.google-analytics.com
Usage:
  reporter event [flags]

Flags:
  -a, --action string     event action
  -c, --category string   event category
  -h, --help              help for event
  -l, --label string      event label
  -v, --value string      event value

2022/02/11 11:41:59 Post "https://www.google-analytics.com/collect": x509: certificate is valid for pfsense-pfBNG-DNSBL-608700ab405a6, not www.google-analytics.com
</pre>

**Additional context**

Additionally, it would be nice if we could disable the callback to GA. I understand why this is here, but for privacy reasons, having a required callback to GA is not ideal.

### PR DESCRIPTION
**Pull request by shubham-bansal96**
## Description
If there an issue while connecting with Google Analytics then fission fail to start. This fix logs error instead of existing with non-zero exit code and failing installation.

## Which issue(s) this PR fixes:
Fixes #2351

## Testing

Enable analytics to true in skaffold file

1. Provided wrong GA URL and fission fails to start with old changes.
2. Provided wrong GA url, now fission is working fine with new changes even if connection was not successfully established GA.
3. Provided correct GA url, and fission is working as expected with new changes.
 
## Checklist:

- [x] I ran tests as well as code linting locally to verify my changes. 
- [x] I have done manual verification of my changes, changes working as expected.
- [x] I have added new tests to cover my changes.
- [x] My changes follow contributing guidelines of Fission.
- [ ] I have signed all of my commits.

### CODE REVIEW

File: pkg/tracker/tracker.go [hunk 1]
```diff
@@ -51,7 +51,11 @@ func init() {
 	if err != nil {
 		panic(err)
 	}
-	Tracker = &tracker{gaPropertyID: os.Getenv(GA_TRACKING_ID), cid: id.String()}
+	Tracker = &tracker{
```
Comment (sanketsudake) [inline pkg/tracker/tracker.go:54]: Lets move this code out of init and define a function to create a tracker.

```
NewTracker() error
```

File: pkg/tracker/tracker.go [hunk 2]
```diff
@@ -51,7 +51,11 @@ func init() {
...
+		gaPropertyID: os.Getenv(GA_TRACKING_ID),
+		cid:          id.String(),
+		gaAPIURL:     "https://www.google-analytics.com/collect",
```
Comment (sanketsudake) [inline pkg/tracker/tracker.go:57]: Please define env var `GA_TRACKING_URL`. If empty we should set default `https://www.google-analytics.com/collect`

**Review by sanketsudake — CHANGES_REQUESTED** [review]

File: pkg/tracker/tracker.go [hunk 3]
```diff
@@ -51,7 +51,11 @@ func init() {
 	if err != nil {
 		panic(err)
 	}
-	Tracker = &tracker{gaPropertyID: os.Getenv(GA_TRACKING_ID), cid: id.String()}
+	Tracker = &tracker{
+		gaPropertyID: os.Getenv(GA_TRACKING_ID),
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply pkg/tracker/tracker.go:55]: check for GA_TRACKING_ID is already there in SendEvent function

if t.gaPropertyID == "" {
		return errors.New("tracker.SendEvent: GA_TRACKING_ID env not set")
	}

File: pkg/tracker/tracker_test.go [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+		cid: id.String(),
+	}
+
+	event := &Event{
+		Label: "play",
+		Value: "value",
+	}
+
+	//Testcase 1
+	t.Run("GA Tracking ID should not be empty", func(test *testing.T) {
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply pkg/tracker/tracker_test.go]: done

File: pkg/tracker/tracker_test.go [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+		resp := tracker.SendEvent(context.Background(), *event)
+		assert.Nil(test, resp, "error must be nil if response is ok from google analytics")
+	})
+}
+
+func MockServer(status int, encodeValue interface{}) *httptest.Server {
+	f := func(w http.ResponseWriter, r *http.Request) {
+		w.WriteHeader(status)
+		w.Header().Set("Content-Type", "application/json")
+		json.NewEncoder(w).Encode(encodeValue)
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply pkg/tracker/tracker_test.go]: done

File: pkg/tracker/tracker_test.go [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+	//Testcase 4
+	t.Run("Google Analytics response should be OK", func(test *testing.T) {
+		server := MockServer(200, "")
+		tracker.gaAPIURL = server.URL
+		resp := tracker.SendEvent(context.Background(), *event)
+		assert.Nil(test, resp, "error must be nil if response is ok from google analytics")
+	})
+}
+
+func MockServer(status int, encodeValue interface{}) *httptest.Server {
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply pkg/tracker/tracker_test.go]: done

File: pkg/tracker/tracker.go (hunk 1 above)
Comment (shubham-bansal96) [reply pkg/tracker/tracker.go:66]: done

File: pkg/tracker/tracker.go (hunk 2 above)
Comment (shubham-bansal96) [reply pkg/tracker/tracker.go]: done

File: pkg/tracker/tracker_test.go [hunk 7]
```diff
@@ -0,0 +1,142 @@
...
+		}
+
+		tracker := &tracker{
+			gaPropertyID: "UA-000000-2",
+			gaAPIURL:     "/",
+			cid:          id.String(),
+		}
+		for _, test := range []struct {
+			name     string
+			request  *request
```
Comment (sanketsudake) [inline pkg/tracker/tracker_test.go:67]: I see we are using same tracker all request structure instances. 
Do we really need request type or we should be fine event only for tests ?

File: pkg/tracker/tracker.go [hunk 8]
```diff
@@ -28,15 +28,16 @@ import (
 )
 
 const HTTP_TIMEOUT = 5 * time.Second
-const GA_API_URL = "https://www.google-analytics.com/collect"
 const GA_TRACKING_ID = "GA_TRACKING_ID"
+const GA_API_URL = "GA_API_URL"
```
Comment (sanketsudake) [inline pkg/tracker/tracker.go:32]: Can we please reduce this block ?

```
const (
     HTTP_TIMEOUT = 5 * time.Second
    GA_TRACKING_ID string = "GA_TRACKING_ID"
     GA_API_URL string = "GA_API_URL"
)
```
Also please add types for constants as appropriate.

**Review by sanketsudake — CHANGES_REQUESTED** [review]

File: pkg/tracker/tracker.go [hunk 9]
```diff
@@ -46,19 +47,31 @@ type (
 	}
 )
 
-func init() {
+func NewTracker() error {
 	id, err := uuid.NewV4()
 	if err != nil {
-		panic(err)
+		return errors.New("tracker.NewTracker: error generating new UUID")
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply pkg/tracker/tracker.go]: done

File: cmd/reporter/main.go [hunk 10]
```diff
@@ -17,14 +17,18 @@ limitations under the License.
...
 )
 
 func main() {
+	logger := loggerfactory.GetLogger()
+	defer logger.Sync()
+
 	err := app.App().Execute()
 	if err != nil {
-		log.Fatal(err)
+		logger.Error("error occurred while establishing connection with google analytics", zap.Error(err))
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply cmd/reporter/main.go]: done

File: pkg/tracker/tracker.go [hunk 11]
```diff
@@ -46,19 +50,31 @@ type (
 	}
 )
 
-func init() {
+func NewTracker() error {
```
Comment (sanketsudake) [inline pkg/tracker/tracker.go:53]: Sorry just noticed this.
Can we please return tracker from this method ?

We should get rid of above global variable.
```
var Tracker *tracker
```

```
func NewTracker() (*tracker, error)
```

You may need to change tracker type to Tracker so that it can be exported.

So existing tracker type will become `type Tracker`

**Review by sanketsudake — CHANGES_REQUESTED** [review]

File: cmd/reporter/app/cmd_event.go [hunk 12]
```diff
@@ -51,6 +51,11 @@ func eventCommandHandler(cmd *cobra.Command, args []string) error {
 	}
 
 	ctx := context.Background()
+
+	err = tracker.NewTracker()
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply cmd/reporter/app/cmd_event.go]: done

File: pkg/tracker/tracker.go (hunk 11 above)
Comment (shubham-bansal96) [reply pkg/tracker/tracker.go]: done

File: pkg/tracker/tracker_test.go [hunk 13]
```diff
@@ -0,0 +1,133 @@
...
+	"log"
+	"net/http"
+	"net/http/httptest"
+	"os"
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+)
+
+type request struct {
```
[the remark this answers is not in the document]
Comment (shubham-bansal96) [reply pkg/tracker/tracker_test.go]: done

File: cmd/reporter/app/cmd_event.go [hunk 14]
```diff
@@ -51,7 +51,12 @@ func eventCommandHandler(cmd *cobra.Command, args []string) error {
 	}
 
 	ctx := context.Background()
-	return tracker.Tracker.SendEvent(ctx, event)
+
+	tracker, err := tracker.NewTracker()
```
Comment (sanketsudake) [inline cmd/reporter/app/cmd_event.go:55]: Since package name is tracker and variable name is also tracker.
Can you please rename variable name ?

```
t, err := tracker.NewTracker()
t.SendEvent
```

File: pkg/tracker/tracker_test.go [hunk 15]
```diff
@@ -0,0 +1,127 @@
...
+					assert.Equal(testing, err.Error(), test.expected.Error())
+				}
+			})
+		}
+	})
+
+	t.Run("SendEvent", func(test *testing.T) {
+
+		os.Setenv(GA_TRACKING_ID, "UA-000000-2")
+		resp, err := NewTracker()
```
Comment (sanketsudake) [inline pkg/tracker/tracker_test.go:53]: ```t, err := NewTracker()```

File: pkg/tracker/tracker_test.go [hunk 16]
```diff
@@ -0,0 +1,127 @@
...
+				expected: nil,
+				status:   http.StatusOK,
+			},
+		} {
+			t.Run(test.name, func(testing *testing.T) {
+				server := MockHTTPServer(test.status, "")
+				defer server.Close()
+				resp.gaAPIURL = server.URL
+
+				resp := resp.SendEvent(context.Background(), *test.request)
```
Comment (sanketsudake) [inline pkg/tracker/tracker_test.go:104]: we override resp here earlier defined resp. This should be better once we rename earlier `resp` def to `t`

**Review by sanketsudake — CHANGES_REQUESTED** [review]

File: pkg/tracker/tracker_test.go (hunk 16 above)
Comment (shubham-bansal96) [reply pkg/tracker/tracker_test.go]: I have rename resp defined earlier as tr not t, because t is already a name of testing.T.

**Review by sanketsudake — APPROVED** [review]
