### PR TITLE
handle addr when port is passed in host:port format in the StartServer func

### LINKED ISSUE #2744: the PPROF doesn't work because of too many colons in address
**Fission/Kubernetes version**
v1.18.0

<pre>
$ fission version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

**To Reproduce**

set PPROF_ENABLED=true
**Expected result**

pprof works well
**Actual result**
2023-03-20T07:04:50.454Z	INFO	httpserver/server.go:17	starting server	{"service": "pprof", "addr": ":localhost:6060"}
2023-03-20T07:04:50.454Z	ERROR	httpserver/server.go:21	server error	{"service": "pprof", "addr": ":localhost:6060", "error": "listen tcp: address :localhost:6060: too many colons in address"}
**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
## Description

This PR ensures to pass the correct value of addr in case when port is passed in `host:port` format in the [StartServer](https://github.com/fission/fission/blob/main/pkg/utils/httpserver/server.go#L11) func.
## Which issue(s) this PR fixes:

Fixes #2744

## Checklist:

- [x] I ran tests as well as code linting locally to verify my changes. 
- [x] I have done manual verification of my changes, changes working as expected.
- [ ] I have added new tests to cover my changes.
- [x] My changes follow contributing guidelines of Fission.
- [x] I have signed all of my commits.

### CODE REVIEW

File: pkg/utils/httpserver/server.go [hunk 1]
```diff
@@ -4,13 +4,20 @@ import (
...
 	"go.uber.org/zap"
 )
 
 func StartServer(ctx context.Context, log *zap.Logger, svc string, port string, handler http.Handler) {
+	var addr string
+	if strings.Contains(port, ":") {
+		addr = port
+	} else {
+		addr = fmt.Sprintf(":%s", port)
+	}
```
Comment (NikhilSharmaWe) [inline pkg/utils/httpserver/server.go:18]: This ensures that if the port is passed as `host:port` like in the case when pprof is **enabled** (like `localhost:6060`) format then do not add extra `:` in the addr. The addr value in other cases is passes like `:port` which means that the server will listen and serve for all hosts at port equal to `port`.

**Review by shubham-bansal96 — APPROVED** [review]

File: pkg/utils/httpserver/server.go [hunk 2]
```diff
@@ -4,13 +4,20 @@ import (
...
 	"fmt"
 	"net/http"
+	"strings"
 
 	"go.uber.org/zap"
 )
 
 func StartServer(ctx context.Context, log *zap.Logger, svc string, port string, handler http.Handler) {
+	var addr string
+	if strings.Contains(port, ":") {
```
Comment (sanketsudake) [inline pkg/utils/httpserver/server.go:14]: if !strings.Contains(port, ":") {
      port = fmt.Sprintf(":%s", port)
)

can be done in single condition.

**Review by sanketsudake — APPROVED** [review]
